.github/pull_request_template.md

Adding pull request template for future work

adding pull request template

---

maltd-frontend/.storybook/main.js
maltd-frontend/README.md
maltd-frontend/package-lock.json
maltd-frontend/package.json

Add storybook and setup path for stories, so we can start working on our first base components.
I have been able to run `npm run storybook` and see my storybook on the browser. Currently there are no stories but when stories are added, they will show up here.

Storybook!

---

maltd-frontend/src/App.js
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/ListElement.stories.js
maltd-frontend/src/components/base/ListElement/ListElement.test.js
maltd-frontend/src/components/base/ListElement/__snapshots__/ListElement.test.js.snap

This PR adds the basic list element base component and story. Jira tickets:
- https://justice.gov.bc.ca/jira/browse/MDYNAMICS-403
- https://justice.gov.bc.ca/jira/browse/MDYNAMICS-404
Unit tests, and visually through storybook

MALTD: 403/404

---

maltd-frontend/src/components/composite/UserSearch/UserSearch.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.test.js

Add tests that were removed to ensure loading state works fine in user search composite component
It is only a unit test being added, and the new tests pass.

Add tests that were removed

---

maltd-frontend/src/components/base/GeneralButton/GeneralButton.css
maltd-frontend/src/components/base/InputField/InputField.css
maltd-frontend/src/components/composite/UserSearch/UserSearch.css
maltd-frontend/src/components/composite/UserSearch/UserSearch.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.stories.js
maltd-frontend/src/components/page/MainPage/MainPage.css
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/index.css

This PR adds the user not exist story to the UserSearch component and fixes the font defect.
The corresponding Storybook story has been created to confirm that the user search component looks and behaves as it should.
Code style and potential errors/issues have been taken care of by ESLint and Prettier.

UserSearch Component Modification

---

api/src/BcGov.Malt.Web/Startup.cs

Added CORS for any origin
Service setup using built-in classes.  Compiles fine.

Enable CORS for any origin

---

api/src/BcGov.Malt.Web/Services/InMemoryUserSearchService.cs

Added initializing example email addresses on the in memory mock user search service as required by Shreyas.

Add example email addresses to in memory search service

---

maltd-frontend/src/App.js
maltd-frontend/src/components/base/GeneralButton/GeneralButton.js
maltd-frontend/src/components/base/GeneralButton/GeneralButton.stories.js
maltd-frontend/src/components/base/GeneralButton/__snapshots__/GeneralButton.test.js.snap
maltd-frontend/src/components/base/InputField/InputField.js
maltd-frontend/src/components/base/InputField/InputField.stories.js
maltd-frontend/src/components/base/InputField/InputField.test.js
maltd-frontend/src/components/base/InputField/__snapshots__/InputField.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.css
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/__snapshots__/ListElement.test.js.snap
maltd-frontend/src/components/base/NavBar/NavBar.css
maltd-frontend/src/components/base/NavBar/NavBar.js
maltd-frontend/src/components/base/NavBar/NavBar.stories.js
maltd-frontend/src/components/base/NavBar/NavBar.test.js
maltd-frontend/src/components/base/NavBar/__snapshots__/NavBar.test.js.snap
maltd-frontend/src/components/composite/UserAccess/UserAccess.css
maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.stories.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.test.js
maltd-frontend/src/components/composite/UserAccess/__snapshots__/UserAccess.test.js.snap
maltd-frontend/src/components/composite/UserSearch/UserSearch.css
maltd-frontend/src/components/composite/UserSearch/UserSearch.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.stories.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.test.js
maltd-frontend/src/components/composite/UserSearch/__snapshots__/UserSearch.test.js.snap
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js
maltd-frontend/src/components/page/MainPage/__snapshots__/MainPage.test.js.snap

This PR adds the main page component which links the user search and user access composite components. It addresses the main sprint 2 goal from the frontend side of things.
Storybook, Jest tests and visually
Also, working with API endpoints and checking data is correct
More tests need to be added but not a blocker for this PR

Main Page, Navbar & Cleanup

---

api/src/BcGov.Malt.Web/Services/InMemoryUserSearchService.cs

Ading First and Last names to in memory user service
build locally
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes

add First ad Last Names

---

maltd-frontend/.eslintrc.js
maltd-frontend/package-lock.json
maltd-frontend/package.json
maltd-frontend/src/App.js
maltd-frontend/src/components/base/BackIcon/BackIcon.css
maltd-frontend/src/components/base/BackIcon/BackIcon.js
maltd-frontend/src/components/base/BackIcon/BackIcon.stories.js
maltd-frontend/src/components/base/BackIcon/BackIcon.test.js
maltd-frontend/src/components/base/GeneralButton/GeneralButton.js
maltd-frontend/src/components/base/GeneralButton/GeneralButton.stories.js
maltd-frontend/src/components/base/GeneralButton/GeneralButton.test.js
maltd-frontend/src/components/base/InputField/InputField.js
maltd-frontend/src/components/base/InputField/InputField.stories.js
maltd-frontend/src/components/base/InputField/InputField.test.js
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/ListElement.stories.js
maltd-frontend/src/components/base/NavBar/NavBar.js
maltd-frontend/src/components/base/NavBar/NavBar.stories.js
maltd-frontend/src/components/base/NavBar/NavBar.test.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.stories.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.test.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.stories.js
maltd-frontend/src/components/composite/UserSearch/UserSearch.test.js
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js
maltd-frontend/src/index.js

This PR adds a back button component used on the screen to get back to the user search from the view user access screen.
Note: the only reason there are a lot of changed files is because I cleaned up a way an eslint rule was being disabled.
Visually and unit tests

Add back button component

---

.github/workflows/main.yml
maltd-frontend/src/components/base/BackIcon/__snapshots__/BackIcon.test.js.snap

This PR sets up the github action to run our jest tests on every push.
Tested by pushing up changes and seeing the build and tests pass.

Jest GitHub action

---

maltd-frontend/src/components/base/NavBar/NavBar.js
maltd-frontend/src/components/base/NavBar/NavBar.stories.js
maltd-frontend/src/components/base/NavBar/NavBar.test.js
maltd-frontend/src/components/base/NavBar/__snapshots__/NavBar.test.js.snap
maltd-frontend/src/components/page/MainPage/MainPage.js

Cleanup navbar since it doesnt need an unauthenticated state - user will always be logged in when using app.
Storybook and jest tests

Cleanup navbar

---

package-lock.json

Remove unused package-lock.json file

remove package-lock.json file

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Controllers/ProjectsController.cs
api/src/BcGov.Malt.Web/Controllers/UsersController.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Startup.cs
api/src/BcGov.Malt.Web/appsettings.Development.json
api/src/BcGov.Malt.Web/appsettings.json

This PR contains changes to enable logging via Serilog to the console. Diagnostic logs were added to each API end point.
Build and run services locally and observe console output.

Added Serilog logging and diagnostic logging statements

---

api/src/BcGov.Malt.Web/Startup.cs

Add calls to CORS config to enable any method and any header. All CORS ahead!
Not explicitly tested since using supported API endpoints from standard library.
- [x My code follows the style guidelines of this project

Alow any header and any method on CORS

---

api/src/BcGov.Malt.Web/Program.cs

This change contains a missing using statement preventing app compilation.
Solution successfully compiles now.

Add missing using statement preventing compilation

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Startup.cs

Nuget package for jwt 
Startup code for authentication
- [x ] New feature (non-breaking change which adds functionality)
build locally and with local appsettings.json
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

 nuget package for jwt & authentication

---

api/src/BcGov.Malt.Web/Startup.cs

removed a fully qualified package name, added Serilog, removed the exception from return statements
Build and ran the application locally

MDYNAMICS-447 - review comments from PR 49 (/bcgov/maltd/pull/49)

---

maltd-frontend/src/components/base/Dropdown/__snapshots__/Dropdown.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.css
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/__snapshots__/ListElement.test.js.snap
maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/composite/UserAccess/__snapshots__/UserAccess.test.js.snap
maltd-frontend/src/components/page/MainPage/MainPage.js

Moved the No Projects message to the proper column.  

move No Projects message to different column

---

maltd-frontend/src/components/page/MainPage/MainPage.js

Try to fix deployment issue by using env variable to pull base url
Testing in openshift with @emuthiah and @pbolduc 

Use process.env to check for env variable for base url

---

maltd-frontend/src/components/page/MainPage/MainPage.js

use REACT_APP_ for env variables

---

api/src/BcGov.Malt.Web/Startup.cs

This PR contains fixes where my previous PR did not compile.
Compiles now.

Fix errors in Startup class resulting from previous merge.

---

api/src/BcGov.Malt.Web.Tests/BcGov.Malt.Web.Tests.csproj
api/src/BcGov.Malt.Web.Tests/Models/Authorization/TokenTests.cs
api/src/BcGov.Malt.Web/Models/Authorization/Token.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/IResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/ITokenCache.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs
api/src/BcGov.Malt.Web/Services/OAuthTokenService.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/TokenCache.cs
api/src/BcGov.Malt.Web/Startup.cs

This PR cleans up classes and interfaces that were in the a single .cs file. Also adds unit tests on the Token class to test to ensure the expiration of the token is computed correctly.
Run unit tests via Visual Studio

Clean up files/classes and add Token expiration unit tests

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfiguration.cs
api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfigurationCollection.cs
api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfigurationExtensions.cs
api/src/BcGov.Malt.Web/Models/Dynamics/SystemUser.cs
api/src/BcGov.Malt.Web/Models/IDIR.cs
api/src/BcGov.Malt.Web/Models/Project.cs
api/src/BcGov.Malt.Web/Services/InMemoryProjectService.cs
api/src/BcGov.Malt.Web/Services/InMemoryUserSearchService.cs
api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Services/ProjectService.cs
api/src/BcGov.Malt.Web/Services/TokenAuthorizationHandler.cs
api/src/BcGov.Malt.Web/Services/TokenCache.cs
api/src/BcGov.Malt.Web/Startup.cs

Contains changes to load projects from configuration. Warnings fixed by either updating code or adding disable for items like no XML comments on public members.  References to Polly (for retry) were added but not configured yet

Add projects from configuration, resolve compliation warnings

---

maltd-frontend/package-lock.json
maltd-frontend/package.json
maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/NavBar/NavBar.js
maltd-frontend/src/components/base/NavBar/__snapshots__/NavBar.test.js.snap
maltd-frontend/src/components/base/XIcon/XIcon.stories.js
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/__snapshots__/MainPage.test.js.snap
maltd-frontend/src/storyshots.test.js

Start cleanup of frontend codebase:
- add tests for storybook `.stories.js` files
- minor UI modifications
- cleanup
Locally and jest

Clean up #1

---

maltd-frontend/sonar-project.properties

Removing .stories.js from sonar exclusions

Removing .stories.js from sonar exclusions

---

maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js

- Change MainPage.js to a stateful component due to lack of testing support for react state hooks
- Add test cases to improve coverage
- add tests, code coverage, cleanup
Jest, locally
this PR fixes jira ticket: **https://justice.gov.bc.ca/jira/browse/MDYNAMICS-489** but is only part 2, there will be some more work required

Cleanup #2

---

api/README.md

Update API README.md with respect to configuration

Move the environment variables configuration top

---

maltd-frontend/.babelrc
maltd-frontend/package-lock.json
maltd-frontend/package.json
maltd-frontend/setupJest.js
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js
maltd-frontend/src/setupTests.js

Major refactoring of the api calls from the frontend to the backend, added a lot of unit tests to improve test coverage of async function calls.
Test coverage drastically improved, now sitting at 93%! and quality gate passing! 💯 
Frontend still working to communicate with backend, more testing needs to be done to ensure new backend code works well.
Tests pass, old and new
this PR fixes jira ticket: **https://justice.gov.bc.ca/jira/browse/MDYNAMICS-489**

Cleanup #3

---

maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js

Further try to improve test coverage 😄 
Fix small bug with user search functionality

Cleanup #4

---

maltd-frontend/sonar-project.properties

Exclude HOC from sonar scan for test coverage - just using a library and making calls

Add exclusion

---

maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js

Adding in some missing tests as per sonarqube coverage results.

Add missing tests for keyenter and onlogout

---

api/README.md
api/src/BcGov.Malt.Web/Models/Configuration/ProjectResource.cs
api/src/BcGov.Malt.Web/Services/IUserSearchService.cs
api/src/BcGov.Malt.Web/Services/InMemoryUserSearchService.cs
api/src/BcGov.Malt.Web/Services/LdapUserSearchService.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/Authentication.cs

Add classes to support Sharepoint SAML authentication. Add method to IUserSearchService to get UPN. Updated docs.
Run locally testing against the Test Org.

Pb sharepoint auth

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Controllers/ProjectsController.cs
api/src/BcGov.Malt.Web/Controllers/UsersController.cs
api/src/BcGov.Malt.Web/Features/Projects/AddUserToProject.cs
api/src/BcGov.Malt.Web/Features/Projects/ListProjects.cs
api/src/BcGov.Malt.Web/Features/Projects/RemoveUserFromProject.cs
api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Features/Users/Search.cs
api/src/BcGov.Malt.Web/Models/Project.cs
api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/IResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/InMemoryUserManagementService.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs
api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Services/ResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/Authentication.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs
api/src/BcGov.Malt.Web/Startup.cs

This change has the initial work to really search dynamics if a user is a member or not.  This has a **breaking change** with respect to fetching of the user is a member of which projects.  The front end code will require checking the list of projects.  The valid values for status are: not-member, member, error
A member result:
```json
{
"projects":[
{
"id":"5a36bd4bf2d4ba5caa906a5e3662494980f1f67a",
"name":"Corrections Dev",
"resources":[
{
"type":"Dynamics",
"status":"member"
}
]
}
],
"id":"2d4ba5caa906a5e36624949",
"username":"FLAST",
"firstName":"first",
"lastName":"last",
"email":"first.last@gov.bc.ca"
}
```
Not a member result:
```json
{
"projects":[
{
"id":"5a36bd4bf2d4ba5caa906a5e3662494980f1f67a",
"name":"Corrections Dev",
"resources":[
{
"type":"Dynamics",
"status":"not-member" …
```

Add support to search dynamics for membership.

---

api/src/BcGov.Malt.Web/Services/InMemoryUserSearchService.cs

This fixes exception being thrown during unit tests.

Fix issue with failing unit tests

---

api/src/BcGov.Malt.Web/Startup.cs

Moves CORS initialization before routing initialization.

Setup CORS before routing

---

api/src/BcGov.Malt.Web/Startup.cs

This reverts commit 18dee68f9d8814734fefc59066a58d4bebf1a5a1.

Revert "Merge pull request #90 from bcgov/pb-fix-cors-init-settings"

---

maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/__snapshots__/ListElement.test.js.snap
maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.stories.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.test.js
maltd-frontend/src/components/composite/UserAccess/__snapshots__/UserAccess.test.js.snap
maltd-frontend/src/components/page/MainPage/MainPage.js

Integrates new backend changes to `/api/users/{username}` call in the way projects are returned
Locally, more changes will be required once add and remove functionality is finalized on backend side of things

Start integrating new backend

---

maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/composite/UserAccess/UserAccess.js

Fixes this code smell: https://sonarqube-wiqfxv-tools.pathfinder.gov.bc.ca/project/issues?id=maltd-frontend&open=AXDFHM6rDbF3hiO05UQ0&resolved=false&types=CODE_SMELL
Tested on sonarqube

fix code smell for cognitive complexity

---

maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/Dropdown/Dropdown.js
maltd-frontend/src/components/base/Dropdown/__snapshots__/Dropdown.test.js.snap
maltd-frontend/src/components/composite/UserAccess/__snapshots__/UserAccess.test.js.snap

dont list project type in project list (dropdown)

fix dropdown list element

---

maltd-frontend/src/components/page/MainPage/MainPage.js

Add bearer keycloak token to all backend requests in authorization header
It has not been tested currently - backend will need to be configured for this to work.

add bearer keycloak token to all requests

---

package-lock.json

Removed the copy of package-lock file from the root.
Removed a file.

Remove package-lock from root

---

maltd-frontend/package.json
maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/ListElement.stories.js
maltd-frontend/src/components/base/ListElement/ListElement.test.js
maltd-frontend/src/components/base/ListElement/__snapshots__/ListElement.test.js.snap
maltd-frontend/src/components/composite/UserAccess/UserAccess.test.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js

Improving test coverage
moved regenerator-runtime into dependencies instead of dev-dependency

Improvements to test coverage (cont.)

---

api/src/BcGov.Malt.Web/Models/Dynamics/SystemUser.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/IResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/ResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs

Adds feature to add, enable and disable users in Dynamics CRM
Tested against Corrections Dynamics DEV environment.

Dynamics add remove user

---

maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/base/ListElement/ListElement.stories.js
maltd-frontend/src/components/base/ListElement/ListElement.test.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.css
maltd-frontend/src/components/composite/UserAccess/UserAccess.js
maltd-frontend/src/components/composite/UserAccess/UserAccess.test.js
maltd-frontend/src/components/composite/UserAccess/__snapshots__/UserAccess.test.js.snap
maltd-frontend/src/components/composite/UserSearch/UserSearch.js
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js

Adds final integrations between frontend and backend to be able to:
- display projects and resources correctly
- add and remove projects correctly
- display error message when trying to add a duplicate project
Locally
this PR fixes jira ticket: **https://justice.gov.bc.ca/jira/browse/MDYNAMICS-488**

Integrations between FE and BE (final stages for phase 1)

---

api/src/BcGov.Malt.Web/Startup.cs
api/src/BcGov.Malt.Web/appsettings.json

This change adds JWT validation and require authentication on API calls.
Tested locally

Jwt validation

---

maltd-frontend/src/components/page/MainPage/MainPage.test.js

Add more tests to help improve the coverage based on report shown at https://sonarqube-wiqfxv-tools.pathfinder.gov.bc.ca/component_measures?id=maltd-frontend&metric=branch_coverage&selected=maltd-frontend%3Asrc%2Fcomponents%2Fpage%2FMainPage%2FMainPage.js
Jest

Add even more tests, make coverage even more awesome

---

maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js
maltd-frontend/src/modules/HelperFunctions.js

Add in fixes for handling duplicate adds and showing resources on add properly

Final fixes and updates to add/remove

---

maltd-frontend/src/components/page/MainPage/MainPage.test.js

Improve test coverage (remove user case)

---

maltd-frontend/src/components/page/MainPage/MainPage.js

Add page refresh on 401 error case

add 401 error handling

---

maltd-frontend/src/components/page/MainPage/MainPage.js

Async Await!

---

maltd-frontend/src/components/page/MainPage/MainPage.test.js

add more test cases for 401 cases, partial add/remove

EVEN MORE TESTS

---

api/src/BcGov.Malt.Web.Tests/Services/InMemoryUserManagementServiceTests.cs

This fixes an incorrect unit test assertion.
Unit tests now work locally.

Fixed incorrect assertion in unit test

---

postman-tests/MALT-Api-E2E-Flow.postman_collection.json
postman-tests/MALT-Api-Get-Projects.postman_collection.json
postman-tests/MALT-Api-Get-Users.postman_collection.json
postman-tests/MALT-Api-User-Search.postman_collection.json
postman-tests/README.md
postman-tests/end-to-end-flow-data-file.json
postman-tests/get-user-data-file.json
postman-tests/malt-dev-env.postman_environment.json
postman-tests/search-user-data-file.json

PR includes workflow tests for postman and document update.
Tested on Postman collection runner
this PR fixes jira ticket: https://justice.gov.bc.ca/jira/browse/MDYNAMICS-436

Postman collections refactor

---

maltd-frontend/src/components/page/MainPage/MainPage.js

Add checks for undefined values in error checks

Defensive error handling

---

api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

Adding a 15 second timeout to SharePoint requests, as some errors can take several minutes to resolve which are blocking the response of the parent request

Adding 15 second timeout to sharepoint calls

---

maltd-frontend/package.json

Updating homepage to correct JAG Proxy URI Issue

---

maltd-frontend/Dockerfile
maltd-frontend/docker-compose.yml

Dockerize FE app, can use `docker-compose up -d --build` to start and `docker-compose stop` to stop service

Dockerize fe app

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Features/Projects/ListProjects.cs
api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfigurationExtensions.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

Update the dependencies versions and resolved a couple of 'async' compiler warnings.
- reference update

Updated project references and resolve compile warnings about async

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/HealthChecks/AccessTokenHealthCheck.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/AccessTokenLoader.cs
api/src/BcGov.Malt.Web/Services/ITokenCache.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/ISamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/TokenCache.cs
api/src/BcGov.Malt.Web/Startup.cs

This PR contains two changes.  
- A health check endpoint /health that will check each project resource to ensure an access token can be fetched. These tokens are not cached
- A startup task that fetches and caches access tokens for each project resource.
this PR fixes jira ticket: MDYNAMICS-580, MDYNAMICS-581

Added heath check and startup fetching of tokens

---

api/src/BcGov.Malt.Web/HealthChecks/AccessTokenHealthCheck.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/AccessTokenLoader.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticationException.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Startup.cs

Fixed issue where IoC was not able to fetch dependencies
Ran locally against the TEST Org

Fixed IoC issues with startup tasks and health checks

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj

This change suppresses some warnings that we being output during the build.

Adjust disable warnings settings

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Program.cs

This change adds support for sending logs to splunk. In addition, various packages were updated.  The app can be configured using `SPLUNK_URL` and `SPLUNK_TOKEN` configuration values. 

Added support to configure logging to splunk

---

api/src/BcGov.Malt.Web/Models/Dynamics/SystemUser.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs
api/src/BcGov.Malt.Web/Services/ResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

This change adds additional logs and properties around dynamics connections.

Add additional logging around dynamics connections

---

api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

Set Auth timeout to 15 seconds and data timeout to 30 seconds.

Add 15 second timeout to http requests

---

api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

Revert "Add 15 second timeout to http requests"

---

api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs

Disable UseAbsoluteReferenceUris

Disable UseAbsoluteReferenceUris to prevent qualified uri 

---

api/src/BcGov.Malt.Web/Infrastructure/ApiGatewayHandler.cs
api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfigurationExtensions.cs
api/src/BcGov.Malt.Web/Models/Configuration/ProjectResource.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Startup.cs

Add delegating handler to apply API Gateway Policy if configured

Add delegating handler to apply API Gateway Policy

---

api/src/BcGov.Malt.Web.Tests/Services/InMemoryUserManagementServiceTests.cs
api/src/BcGov.Malt.Web/Controllers/ProjectsController.cs
api/src/BcGov.Malt.Web/Controllers/UsersController.cs
api/src/BcGov.Malt.Web/Features/Projects/AddUserToProject.cs
api/src/BcGov.Malt.Web/Features/Projects/ListProjects.cs
api/src/BcGov.Malt.Web/Features/Projects/RemoveUserFromProject.cs
api/src/BcGov.Malt.Web/Features/RequestHandlerBase.cs
api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/IResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/IUserManagementService.cs
api/src/BcGov.Malt.Web/Services/InMemoryUserManagementService.cs
api/src/BcGov.Malt.Web/Services/ResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs

The front end will timeout after 30 seconds. This PR adds the use of CancellationTokens to timeout after 29 seconds.  Additional error handling may be required to handle when cancellation is requested.

Add 29 second timeout using cancellation tokens

---

api/src/BcGov.Malt.Web/Infrastructure/ApiGatewayHandler.cs
api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs

Remove tracing of odata calls that were put in place for toubleshooting.

Disable odata tracing

---

maltd-frontend/src/components/hoc/AuthenticationGuard.js
maltd-frontend/src/components/page/MainPage/MainPage.js

This fixes the husky pre-push eslint check.  I dont like how eslint is saying this should be formatted, but I was tired of having to ignore the error and push with `--no-verify` or something like that.

Fix issues causing eslint / prettier to complain on push

---

maltd-frontend/src/components/hoc/AuthenticationGuard.js

This change allows for optionally configure keycloak via it's keyloak.json loading mechanizm.

Keycloak config

---

maltd-frontend/src/components/hoc/AuthenticationGuard.js

Revert previous changes applied around logout and redirect.

revert redirectUri and logout logic

---

maltd-frontend/src/components/hoc/AuthenticationGuard.js

Change how we pull the keycloak settings

refactor getting config

---

maltd-frontend/src/components/page/MainPage/MainPage.js

This changes allows changing the api base path from `/api` to something else for support for deployment environments.

Configurable api base path

---

maltd-frontend/src/index.js

Configure the baseUrl for axios if available.

Set baseUrl if available

---

api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs

This PR is the beginning of a change to adjust the ServicePointManager default outbound connection settings. This is the first PR to log so we can see the defaults on OpenShift prior to making changes.

Adjust service point manager defaults

---

api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs

This is ongoing work to adjust the logging and error handling when there is timeout or other errors

Adjust logging to reduce logging when timeout

---

api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs
maltd-frontend/src/index.js

Change to determine why dev env is failing now

Readd log statement when task was cancelled trying to lookup dynamics

---

maltd-frontend/src/index.js

Try to set javascript request timeouts.

Try to configure axios request timeouts

---

api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/index.js

- adjust axios request time outs
- ignore site groups we do not have access to (forbidden)

Exception handling logging

---

maltd-frontend/src/components/page/MainPage/MainPage.js
maltd-frontend/src/components/page/MainPage/MainPage.test.js
maltd-frontend/src/index.js

attempt to set front end timeout

Adjust trying to set front end timeout

---

api/src/BcGov.Malt.Web/Features/Projects/AddUserToProject.cs
api/src/BcGov.Malt.Web/Features/Projects/RemoveUserFromProject.cs
api/src/BcGov.Malt.Web/Features/RequestHandlerBase.cs
api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Features/Users/Search.cs
api/src/BcGov.Malt.Web/HealthChecks/AccessTokenHealthCheckBase.cs
api/src/BcGov.Malt.Web/HealthChecks/ProjectAccessTokenHealthCheck.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/AccessTokenLoader.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs
api/src/BcGov.Malt.Web/Services/OAuthTokenService.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/TokenAuthorizationHandler.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs
api/src/BcGov.Malt.Web/Startup.cs

- Added ConfigureAwait(false) to internal calls in attempt to avoid blocking on async calls on sync contexts
- disable health checks to avoid extra activity until performance has been resolved

Configure await false all the things

---

api/src/BcGov.Malt.Web/Features/Projects/AddUserToProject.cs
api/src/BcGov.Malt.Web/Features/Projects/RemoveUserFromProject.cs
api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Features/Users/Search.cs
api/src/BcGov.Malt.Web/HealthChecks/AccessTokenHealthCheckBase.cs
api/src/BcGov.Malt.Web/HealthChecks/ProjectAccessTokenHealthCheck.cs
api/src/BcGov.Malt.Web/Infrastructure/ApiGatewayHandler.cs
api/src/BcGov.Malt.Web/Infrastructure/ApiGatewayUriBuilder.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/Services/AccessTokenLoader.cs
api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/OAuthClient.cs
api/src/BcGov.Malt.Web/Services/OAuthTokenService.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/ISamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/TokenAuthorizationHandler.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs

Fixes for use the API gateway with sharepoint
Also removes .ConfigureAwait(false);

Api gateway with sharepoint

---

maltd-frontend/src/components/base/ListElement/ListElement.js
maltd-frontend/src/components/page/MainPage/MainPage.js

few more fixes

---

maltd-frontend/src/__snapshots__/storyshots.test.js.snap
maltd-frontend/src/components/base/ListElement/ListElement.css
maltd-frontend/src/components/base/ListElement/ListElement.js

Grey out delete icon after click

Grey out delete icon after click

---

api/src/BcGov.Malt.Web/Models/SharePoint/User.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/ResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/ISamlAuthenticator.cs
api/src/BcGov.Malt.Web/Services/SharepointResourceUserManagementService.cs
api/src/BcGov.Malt.Web/Services/UserManagementService.cs

This PR addresses issue where an error was being returned adding a user to SharePoint.

Fix issue where error was being returned adding user to sharepoint

---

api/src/BcGov.Malt.Web/Models/Dynamics/SystemUser.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs

This change set or updates the sharepointemailaddress in Dynamics with the user's UPN.

Populate UPN into SharePoint Email Address in dynamics

---

maltd-frontend/src/components/page/MainPage/MainPage.js

This change adds console.error(...) calls if the catch handler is executed.

Add log statements if error handler is executed

---

maltd-frontend/package.json
maltd-frontend/src/components/page/MainPage/MainPage.js

convert value to lower case also before comparison
locally

Convert value to lower case also before comparison (for CAPS idirs)

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/BcGov.Jag.AccountManagement.Client.csproj
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/Extensions.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/IRepository.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/Repository.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/UserApi.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/CurrentUser.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Program.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Shared/RedirectToLogin.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/BcGov.Jag.AccountManagement.Server.csproj
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Controllers/UserController.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Program.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/appsettings.json

has changes to support better data access

Add data access repository and adjust logging configuration

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Shared/MainLayout.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/css/app.css
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/index.html

fix(loader): fix loader for main and manage user screen

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Shared/MainLayout.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/css/app.css

fix(users): fix manage users screen

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Shared/MainLayout.razor.css

fix(css): fix sidebar height

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/Settings.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/css/app.css
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/index.html

fix(tabs): add dynamics and sharepoiunt form

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Components/UserDetails.razor

Fix user details

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/IRepository.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/Repository.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Data/UserApi.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Controllers/UserController.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Dockerfile.rhel8
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Features/Users/Lookup.cs

Handle user not found

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/css/app.css

Fix error message

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/BcGov.Jag.AccountManagement.Client.csproj
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Pages/ManageUsers.razor.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Program.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/Shared/MainLayout.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/_Imports.razor
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/css/app.css
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Client/wwwroot/index.html
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/BcGov.Jag.AccountManagement.Server.csproj
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Program.cs

Feature toast on save

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Program.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/UserManagementService.cs

Resolves issue where the user's access status was not being set after determining.

fix user access now showing results

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/DynamicsResourceUserManagementService.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/SharepointResourceUserManagementService.cs

Fix issue where duplicate trace activity was created.

Remove duplicate acivities when checking if user has access

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Models/Dynamics/Role.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Models/Dynamics/SystemUser.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/DynamicsResourceUserManagementService.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/UserManagementService.cs

Adds the user to the System Administrator role when being added to dynamics.

Add System Administrator role when the user is added to Dynamics
