bcgov/maltd

README.md

This PR adds frontend folder structure to README as discussed in https://github.com/bcgov/maltd/issues/4.

Add frontend folder structure to readme

---

api/src/BcGov.Malt.Web/Controllers/ProjectsController.cs
api/src/BcGov.Malt.Web/Controllers/UsersController.cs
api/src/BcGov.Malt.Web/Models/DetailedUser.cs

This change moves the actions to add or remove a user from a project from ```/api/user``` to ```/api/project``` since we are logically changing a project not a user.
The actions were manually tested using the Swagger UI page.

Move add/remove users from project to project resource

---

.github/workflows/main.yml
.github/workflows/main2.yml
maltd-frontend/cypress/integration/tests/home-page.js
maltd-frontend/cypress/plugins/index.js

This pr makes it so github actions run on pr not just on push
Github actions verified

Run github action on pull request

---

maltd-frontend/README.md

Add env variables setup instructions in frontend readme, as requested.

Add env vars section to readme

---

maltd-frontend/package.json

The `keycloak-js` lib needs to be a dependency and not a dev-dependency because it is needed outside of dev environment (openshift)

Move from dev-dependencies to dependencies for keycloak-js

---

api/src/BcGov.Malt.Web/Models/Configuration/ProjectConfigurationExtensions.cs
api/src/BcGov.Malt.Web/Program.cs
api/src/BcGov.Malt.Web/appsettings.json

This change contains the following changes:
1. Changes to the logging configuration to read from appsettings.json. Other configuration can still come from env vars or user settings (Development).
2. Configuration settings for ClientId and ClientSecret are only required for Dynamics, not Sharepoint.
Check the logging output by running the API.

Pb logging from config config validation

---

api/src/BcGov.Malt.Web/BcGov.Malt.Web.csproj
api/src/BcGov.Malt.Web/Services/LdapUserSearchService.cs

Changes LDAP search to use Novell.Directory.Ldap.NETStandard instead of System.DirectoryServices.Protocols since the latter does not work on OpenShift (Linux/Mac)
For this change, you will need to update your configuration setting for LDAP Username to contained the distinguished name format.

Switch to cross platform LDAP search library

---

api/src/BcGov.Malt.Web/Services/ProjectExtensions.cs
api/src/BcGov.Malt.Web/Startup.cs

This change fixes a startup crash if a valid dynamics project is not added. One service requires IHttpClientFactory and if AddHttpClient() is not called, IHttpClientFactory will have not been added to the services collection
Built and run locally.

Fix start in case HttpClient is not registered

---

maltd-frontend/.env.example
maltd-frontend/src/components/hoc/AuthenticationGuard.js

Portal will only allow users who Authenticate as well as Authorize as users of the portal, as set by specific access role from environment
* Authorization role is set by name in the environment
* After Authentication, keycloak access roles are checked for Authorization role
* If role is present, Portal access is granted
* If role is not present, user is informed they have not authorized and to contact admin for access, and return to IDIR login page
I have built and deployed these changes

Adding Authorization Flow

---

api/src/global.json

Change SDK version to SDK 3.1.106 to allow building on openshift

Adjust the sdk version so we can build on OpenShift

---

api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs

Requests to trust endpoints can return 302 Found which should not be logged as an error. The response still has FedAuth cookie that can be used.

Do not log error when response comes back 302 Found

---

api/src/BcGov.Malt.Web/Program.cs
maltd-frontend/package.json

- removed redundant logging setup config
- adjust how splunk logging is configured
- add a source context to the startup logging of access token issues
- fix pre-commit hook that prevented commits from VS2019 from working see https://github.com/typicode/husky/issues/673#issuecomment-619365933

Change logging

---

api/src/BcGov.Malt.Web/Program.cs

Sets the default connection limit on single host to 50 or to the value of env var DEFAULTCONNECTIONLIMIT. This should reduce the time it takes to get the access tokens by allowing more concurrent requests.

set default connection limit 

---

maltd-frontend/src/components/hoc/AuthenticationGuard.js
maltd-frontend/src/components/page/MainPage/MainPage.js

Change to fetch access token from storage before making xhr request to avoid static token loading and can't search right after login.

Do not use static access token to avoid race condition on first login

---

api/src/BcGov.Malt.Web/Infrastructure/ServicePointManagerConfiguration.cs
api/src/BcGov.Malt.Web/Infrastructure/ThreadPoolConfiguration.cs
api/src/BcGov.Malt.Web/Program.cs

- add code to adjust the threadpool settings - too few threads do not allow the completion of multiple http requests due to blocked on available threads
- move the service point manager configuration into separate class

Adjust threadpool settings, move service point manager

---

api/src/BcGov.Malt.Web/Features/Projects/AddUserToProject.cs
api/src/BcGov.Malt.Web/Features/Projects/RemoveUserFromProject.cs
api/src/BcGov.Malt.Web/Features/RequestHandlerBase.cs
api/src/BcGov.Malt.Web/Features/Users/Lookup.cs
api/src/BcGov.Malt.Web/Services/Sharepoint/SamlAuthenticator.cs

This change adds .ConfigureAwait(false) on nested / parallel calls to prevent blocking on the SynchronizationContext
see [ConfigureAwait FAQ](https://devblogs.microsoft.com/dotnet/configureawait-faq/)
Also add configurable request timeout

Add configurable request timeout using API_TIMEOUT_SECONDS variable

---

api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs

Temporary revert of supplying meta data automatically do to errors one some dynamics instances.

revert populating metadata since it broke stuff

---

api/src/BcGov.Malt.Web/Services/DefaultODataClientFactory.cs
api/src/BcGov.Malt.Web/Services/DynamicsResourceUserManagementService.cs

Enabled using local metadata. Only fetch required columns.

enabled cached metadata, restrict properties returned from dynamics

---

api/src/BcGov.Malt.Web/Services/LdapUserSearchService.cs

This change fixes issue when an account does not have a 'mail' attribute in Active Directory, for example _A accounts.

Access LDAP attributes defensively

---

src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/DynamicsResourceUserManagementService.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/SharepointResourceUserManagementService.cs
src/BcGov.Jag.AccountManagement/BcGov.Jag.AccountManagement/Server/Services/UserManagementService.cs

Lookup the built-in project groups once and cache them.

Avoid looking up SharePoint group names repeatedly
